site_name: Documentation for DoubleHelix
site_url: https://DoubleHelix.github.io
theme:
  name: material
  palette: 
    scheme: slate
    primary: blue grey
    accent: light blue
  logo: logo.jpg
repo_url: https://github.com/DoubleHelix/DoubleHelix
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true